[project]
name = "reboot-on-unplug"
version = "0.1.0"
description = "reboot when a specific USB device is unplugged"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyudev>=0.24.4",
]
